### ISSUE TITLE
Render Script Error:  Exceeded render cost limit

### ISSUE THREAD

**Issue by Mncdk** [Krengus/DU_ASTco#5]
Since 0.72, every ship I have tried to install this script on has given me this error.

I link the core, databank, screens, hubs, in that order, and then paste the script. When I turn on the PB, I just get the error.

**Comment by Krengus** [comment]
Hi, yeah its a new bug NQ added with the function to get max volume from hub.

You can fix it by re doing at least one link on the hub (delete link from one container to hub then create it again)

**Comment by Mncdk** [comment]
> You can fix it by re doing at least one link on the hub (delete link from one container to hub then create it again)

Thanks, that seems to help!
